--@Autor: Martinez Martinez Francisco David
--@Fecha creación: 30/05/2025
--@Descripción: Asignacion de Foreigh Keys


--------------------------------------Fi tablas ---------------------------

-- 
-- TABLE: CERTIFICADO 
--

ALTER TABLE PET_CARE_ADMIN.CERTIFICADO ADD CONSTRAINT fk_inscripcioncurso_certificado 
    FOREIGN KEY (clvInscripcionCurso)
    REFERENCES PET_CARE_ADMIN.INSCRIPCION_CURSO(clvInscripcionCurso)
;


-- 
-- TABLE: CLIENTE 
--

ALTER TABLE PET_CARE_ADMIN.CLIENTE ADD CONSTRAINT fk_municipio_cliente 
    FOREIGN KEY (clvMunicipio)
    REFERENCES PET_CARE_ADMIN.MUNICIPIO(clvMunicipio)
;


-- 
-- TABLE: CONSULTA_MEDICA 
--

ALTER TABLE PET_CARE_ADMIN.CONSULTA_MEDICA ADD CONSTRAINT fk_diagnostico_consultamedico 
    FOREIGN KEY (clvDiagnostico)
    REFERENCES PET_CARE_ADMIN.DIAGNOSTICO(clvDiagnostico)
;

ALTER TABLE PET_CARE_ADMIN.CONSULTA_MEDICA ADD CONSTRAINT fk_mascota_consultamedica 
    FOREIGN KEY (clvMascota)
    REFERENCES PET_CARE_ADMIN.MASCOTA(clvMascota)
;

ALTER TABLE PET_CARE_ADMIN.CONSULTA_MEDICA ADD CONSTRAINT fk_veterinaria_consulta 
    FOREIGN KEY (clvVeterinario)
    REFERENCES PET_CARE_ADMIN.VETERINARIO(clvVeterinario)
;


-- 
-- TABLE: EMPLEADO 
--

ALTER TABLE PET_CARE_ADMIN.EMPLEADO ADD CONSTRAINT fk_empleado_supervisor 
    FOREIGN KEY (clvSupervisorEmp)
    REFERENCES PET_CARE_ADMIN.EMPLEADO(clvEmpleado)
;

ALTER TABLE PET_CARE_ADMIN.EMPLEADO ADD CONSTRAINT fk_veterinaria_empleado 
    FOREIGN KEY (clvVeterinaria)
    REFERENCES PET_CARE_ADMIN.VETERINARIA(clvVeterinaria)
;


-- 
-- TABLE: ESTILISTA 
--

ALTER TABLE PET_CARE_ADMIN.ESTILISTA ADD CONSTRAINT RefEMPLEADO56 
    FOREIGN KEY (clvEstilista)
    REFERENCES PET_CARE_ADMIN.EMPLEADO(clvEmpleado)
;


-- 
-- TABLE: FOTO_MASCOTA 
--

ALTER TABLE PET_CARE_ADMIN.FOTO_MASCOTA ADD CONSTRAINT fk_mascota_foto_mascota 
    FOREIGN KEY (clvMascota)
    REFERENCES PET_CARE_ADMIN.MASCOTA(clvMascota)
;


-- 
-- TABLE: HISTORICO_ESTATUS_PRODUCTOS 
--

ALTER TABLE PET_CARE_ADMIN.HISTORICO_ESTATUS_PRODUCTOS ADD CONSTRAINT fk_estatusproducto_historicoestatusprod 
    FOREIGN KEY (clvEstatusProdInventario)
    REFERENCES PET_CARE_ADMIN.ESTATUS_PROD_INVENTARIO(clvEstatusProdInventario)
;

ALTER TABLE PET_CARE_ADMIN.HISTORICO_ESTATUS_PRODUCTOS ADD CONSTRAINT fk_inventarioveterinaria_historicoestatusprod 
    FOREIGN KEY (clvInventarioVet)
    REFERENCES PET_CARE_ADMIN.INVENTARIO_VETERINARIA(clvInventarioVet)
;


-- 
-- TABLE: HISTORICO_PRECIO 
--

ALTER TABLE PET_CARE_ADMIN.HISTORICO_PRECIO ADD CONSTRAINT fk_producto_historicoprecio 
    FOREIGN KEY (SKU)
    REFERENCES PET_CARE_ADMIN.PRODUCTO(SKU)
;


-- 
-- TABLE: INSCRIPCION_CURSO 
--

ALTER TABLE PET_CARE_ADMIN.INSCRIPCION_CURSO ADD CONSTRAINT fk_curso_inscripcioncurso 
    FOREIGN KEY (clvCurso)
    REFERENCES PET_CARE_ADMIN.CURSO(clvCurso)
;

ALTER TABLE PET_CARE_ADMIN.INSCRIPCION_CURSO ADD CONSTRAINT fk_estilista_inscripcioncurso 
    FOREIGN KEY (clvEstilista)
    REFERENCES PET_CARE_ADMIN.ESTILISTA(clvEstilista)
;


-- 
-- TABLE: INVENTARIO_VETERINARIA 
--

ALTER TABLE PET_CARE_ADMIN.INVENTARIO_VETERINARIA ADD CONSTRAINT fk_estatusprod_inventarioveterinaria 
    FOREIGN KEY (clvEstatusProdInventario)
    REFERENCES PET_CARE_ADMIN.ESTATUS_PROD_INVENTARIO(clvEstatusProdInventario)
;

ALTER TABLE PET_CARE_ADMIN.INVENTARIO_VETERINARIA ADD CONSTRAINT fk_producto_inventarioveterinaria 
    FOREIGN KEY (SKU)
    REFERENCES PET_CARE_ADMIN.PRODUCTO(SKU)
;

ALTER TABLE PET_CARE_ADMIN.INVENTARIO_VETERINARIA ADD CONSTRAINT fk_veterinaria_inventarioveterinaria 
    FOREIGN KEY (clvVeterinaria)
    REFERENCES PET_CARE_ADMIN.VETERINARIA(clvVeterinaria)
;


-- 
-- TABLE: MASCOTA 
--

ALTER TABLE PET_CARE_ADMIN.MASCOTA ADD CONSTRAINT fk_cliente_mascota 
    FOREIGN KEY (clvCliente)
    REFERENCES PET_CARE_ADMIN.CLIENTE(clvCliente)
;


-- 
-- TABLE: MASCOTA_PASEO 
--

ALTER TABLE PET_CARE_ADMIN.MASCOTA_PASEO ADD CONSTRAINT fk_mascota_mascpaseo 
    FOREIGN KEY (clvMascota)
    REFERENCES PET_CARE_ADMIN.MASCOTA(clvMascota)
;

ALTER TABLE PET_CARE_ADMIN.MASCOTA_PASEO ADD CONSTRAINT fk_paseo_mascpaseo 
    FOREIGN KEY (clvPaseo)
    REFERENCES PET_CARE_ADMIN.PASEO(clvPaseo)
;


-- 
-- TABLE: MONITOREO_PASEO 
--

ALTER TABLE PET_CARE_ADMIN.MONITOREO_PASEO ADD CONSTRAINT fk_paseo_monitoreopaseo 
    FOREIGN KEY (clvPaseo)
    REFERENCES PET_CARE_ADMIN.PASEO(clvPaseo)
;


-- 
-- TABLE: MUNICIPIO 
--

ALTER TABLE PET_CARE_ADMIN.MUNICIPIO ADD CONSTRAINT fk_estado_municipios 
    FOREIGN KEY (clvEstado)
    REFERENCES PET_CARE_ADMIN.ESTADO(clvEstado)
;


-- 
-- TABLE: ORDEN_COMPRA 
--

ALTER TABLE PET_CARE_ADMIN.ORDEN_COMPRA ADD CONSTRAINT fk_cliente_ordencompra 
    FOREIGN KEY (clvClienteCompra)
    REFERENCES PET_CARE_ADMIN.CLIENTE(clvCliente)
;

ALTER TABLE PET_CARE_ADMIN.ORDEN_COMPRA ADD CONSTRAINT fk_vendedor_ordencompra 
    FOREIGN KEY (clvVendedorCompra)
    REFERENCES PET_CARE_ADMIN.VENDEDOR(clvVendedor)
;


-- 
-- TABLE: ORDEN_PRODUCTO 
--

ALTER TABLE PET_CARE_ADMIN.ORDEN_PRODUCTO ADD CONSTRAINT fk_ordencompra_ordenproducto 
    FOREIGN KEY (clvOrdenCompra)
    REFERENCES PET_CARE_ADMIN.ORDEN_COMPRA(clvOrdenCompra)
;

ALTER TABLE PET_CARE_ADMIN.ORDEN_PRODUCTO ADD CONSTRAINT fk_producto_ordenproducto 
    FOREIGN KEY (SKU)
    REFERENCES PET_CARE_ADMIN.PRODUCTO(SKU)
;


-- 
-- TABLE: PASEO 
--

ALTER TABLE PET_CARE_ADMIN.PASEO ADD CONSTRAINT fk_vendedor_paseo 
    FOREIGN KEY (clvVendedor)
    REFERENCES PET_CARE_ADMIN.VENDEDOR(clvVendedor)
;


-- 
-- TABLE: PRODUCTO 
--

ALTER TABLE PET_CARE_ADMIN.PRODUCTO ADD CONSTRAINT fk_categoria_producto 
    FOREIGN KEY (clvCategoria)
    REFERENCES PET_CARE_ADMIN.CATEGORIA(clvCategoria)
;


-- 
-- TABLE: SERVICIO_ESTETICA 
--

ALTER TABLE PET_CARE_ADMIN.SERVICIO_ESTETICA ADD CONSTRAINT fk_estilista_servicioestetica 
    FOREIGN KEY (clvEstilista)
    REFERENCES PET_CARE_ADMIN.ESTILISTA(clvEstilista)
;

ALTER TABLE PET_CARE_ADMIN.SERVICIO_ESTETICA ADD CONSTRAINT fk_mascota_servicioestetica 
    FOREIGN KEY (clvMascota)
    REFERENCES PET_CARE_ADMIN.MASCOTA(clvMascota)
;


-- 
-- TABLE: TELEFONO_CLIENTE 
--

ALTER TABLE PET_CARE_ADMIN.TELEFONO_CLIENTE ADD CONSTRAINT fk_cliente_telefono 
    FOREIGN KEY (clvCliente)
    REFERENCES PET_CARE_ADMIN.CLIENTE(clvCliente)
;


-- 
-- TABLE: VENDEDOR 
--

ALTER TABLE PET_CARE_ADMIN.VENDEDOR ADD CONSTRAINT RefEMPLEADO58 
    FOREIGN KEY (clvVendedor)
    REFERENCES PET_CARE_ADMIN.EMPLEADO(clvEmpleado)
;


-- 
-- TABLE: VETERINARIA 
--

ALTER TABLE PET_CARE_ADMIN.VETERINARIA ADD CONSTRAINT fk_vendedor_veterinaria 
    FOREIGN KEY (clvGerente)
    REFERENCES PET_CARE_ADMIN.VENDEDOR(clvVendedor)
;


-- 
-- TABLE: VETERINARIO 
--

ALTER TABLE PET_CARE_ADMIN.VETERINARIO ADD CONSTRAINT RefEMPLEADO57 
    FOREIGN KEY (clvVeterinario)
    REFERENCES PET_CARE_ADMIN.EMPLEADO(clvEmpleado)
;